# Generated by Django 2.2.8 on 2020-01-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='messageaudit',
            old_name='tags',
            new_name='labels',
        ),
    ]
