# Generated by Django 2.2.8 on 2020-01-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200123_1600'),
        ('core', '0002_file_errors'),
    ]

    operations = [
    ]
