# Generated by Django 2.2.10 on 2020-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200212_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmessageaudit',
            name='redactions',
        ),
        migrations.RemoveField(
            model_name='historicalmessageaudit',
            name='restriction',
        ),
        migrations.RemoveField(
            model_name='messageaudit',
            name='redactions',
        ),
        migrations.RemoveField(
            model_name='messageaudit',
            name='restriction',
        ),
        migrations.AddField(
            model_name='historicalmessageaudit',
            name='needs_redaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmessageaudit',
            name='restricted_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='messageaudit',
            name='needs_redaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageaudit',
            name='restricted_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Redaction',
        ),
        migrations.DeleteModel(
            name='RestrictionAuthority',
        ),
    ]
