# Generated by Django 2.2.10 on 2020-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200212_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessageaudit',
            name='is_record',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messageaudit',
            name='is_record',
            field=models.BooleanField(default=True),
        ),
    ]
