# Generated by Django 2.2.10 on 2020-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200214_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('U', 'User'), ('I', 'Importer'), ('S', 'Static'), ('R', 'Restricted')], max_length=1),
        ),
    ]
