# Generated by Django 2.2.10 on 2020-03-06 22:12

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20200306_0802"),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=64),
        ),
    ]
