# Generated by Django 2.2.10 on 2020-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200306_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='md5_hash',
        ),
        migrations.AddField(
            model_name='file',
            name='hash_digest',
            field=models.CharField(default='', max_length=64),
        ),
    ]
