# Generated by Django 2.2.10 on 2020-03-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200313_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='hash_digest',
            new_name='sha256',
        ),
    ]
