# Generated by Django 2.2.10 on 2020-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200318_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='accession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SHA256'),
        ),
        migrations.AlterField(
            model_name='historicalmessageaudit',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmessageaudit',
            name='restricted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageaudit',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageaudit',
            name='labels',
            field=models.ManyToManyField(blank=True, to='core.Label'),
        ),
        migrations.AlterField(
            model_name='messageaudit',
            name='restricted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
