# Generated by Django 2.2.10 on 2020-04-03 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200331_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='unique_paths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
