# Generated by Django 2.2.17 on 2020-11-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_file_unique_paths'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account', 'sent_date'], name='core_messag_account_2f35a9_idx'),
        ),
    ]
