# Generated by Django 2.2.17 on 2020-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201109_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessageaudit',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='messageaudit',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
