# Generated by Django 2.2.7 on 2020-01-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ratom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redacted_subject", models.TextField(null=True)),
                ("redacted_body", models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ratom.Account"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ratom.File"
            ),
        ),
        migrations.AddField(
            model_name="historicalmessage",
            name="redaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ratom.Redaction",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="redaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ratom.Redaction",
            ),
        ),
    ]
