# Generated by Django 2.2.7 on 2020-01-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratom', '0002_auto_20200115_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmessage',
            name='is_record',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_record',
        ),
    ]
