# Generated by Django 2.2.7 on 2020-01-18 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratom', '0002_auto_20200117_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratom.Account'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratom.File'),
        ),
    ]
