# Generated by Django 2.2.7 on 2019-11-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratom", "0002_auto_20191108_1042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.CharField(blank=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message", name="msg_bcc", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="msg_body",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message", name="msg_cc", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="msg_tagged_body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message", name="sent_date", field=models.DateTimeField(),
        ),
    ]
