# Generated by Django 2.2.7 on 2019-11-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratom", "0003_auto_20191116_2147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
