# Generated by Django 2.2.7 on 2019-11-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratom", "0004_auto_20191116_2151"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="directory",
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
