# Generated by Django 2.2.7 on 2020-01-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratom', '0004_auto_20200117_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='mime_type',
            field=models.CharField(max_length=128),
        ),
    ]
