# Generated by Django 2.2.7 on 2020-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratom', '0005_auto_20200117_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmessage',
            name='msg_body',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='msg_subject',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msg_body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msg_subject',
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='subject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
