# Generated by Django 2.2.7 on 2019-11-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ratom", "0005_message_directory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("value", models.TextField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="ratom.Message",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Entities",},
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["label", "value"], name="ratom_entit_label_3cbba3_idx"
            ),
        ),
    ]
