# Generated by Django 2.2.7 on 2020-01-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratom', '0006_auto_20200120_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='account',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='redaction',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='restrictions',
        ),
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
        migrations.DeleteModel(
            name='HistoricalFile',
        ),
        migrations.DeleteModel(
            name='HistoricalMessage',
        ),
    ]
