# Generated by Django 2.2.7 on 2019-11-17 19:41

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratom", "0007_message_msg_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="ratom_messa_data_2b6230_gin"
            ),
        ),
    ]
