# Generated by Django 2.2.7 on 2019-12-10 18:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratom', '0008_auto_20191117_1441'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entity',
            name='ratom_entit_label_3cbba3_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='ratom_messa_data_2b6230_gin',
        ),
        migrations.AlterField(
            model_name='message',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='directory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_from',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_to',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='processor',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
