# Generated by Django 2.2.7 on 2020-01-02 16:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratom', '0009_auto_20191210_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProcessingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=512)),
                ('ingesting_folder', models.IntegerField()),
                ('ingesting_messages', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratom.Collection')),
            ],
            options={
                'unique_together': {('account', 'ingesting_folder')},
            },
        ),
    ]
