# Generated by Django 2.2.7 on 2020-01-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratom", "0009_auto_20191210_1309"),
    ]

    operations = [
        migrations.RenameModel(old_name="Collection", new_name="Account",),
        migrations.RenameField(
            model_name="message", old_name="collection", new_name="account",
        ),
        migrations.RenameField(
            model_name="message", old_name="msg_body", new_name="body",
        ),
        migrations.RenameField(
            model_name="message", old_name="msg_headers", new_name="headers",
        ),
        migrations.RenameField(
            model_name="message", old_name="msg_subject", new_name="subject",
        ),
        migrations.RemoveField(model_name="message", name="msg_tagged_body",),
        migrations.RemoveField(model_name="message", name="processor",),
        migrations.DeleteModel(name="Entity",),
    ]
